### ISSUE TITLE
닫는괄호가 먼저 나올경우 비정상적인 결과가 나옴

### ISSUE THREAD

**Issue by th-kwon** [th-kwon/Calculator#8]
![image](https://user-images.githubusercontent.com/59942506/74906605-dd691b00-53f4-11ea-97ab-8a68553e9112.png)
* 정상적인 결과(38)

![image](https://user-images.githubusercontent.com/59942506/74906621-e659ec80-53f4-11ea-9333-8ba7180349ac.png)
* 비정상적인 결과(19 - 15+4까지만 계산하는 듯함)

* 아래와 같은 식을 넣었으면 오류가 발생하는게 맞을 듯 합니다.

**Comment by LeeJungGeun** [comment]
수정 완료했습니다. 9d45fd7
